-- =====================================================================
--  schema.sql — Esquema de la base de datos (proyecto Supabase: serviciosweb)
--  Ya está APLICADO en el proyecto. Este archivo es la referencia versionada.
--
--  Dos tablas:
--    solicitudes    → cada persona que llena el formulario (lead + estado de pago)
--    contrataciones → ledger de pagos confirmados (alimentado por el webhook)
-- =====================================================================

-- ---------------------------------------------------------------------
--  SOLICITUDES (leads del funnel: login → formulario → pago 50%)
-- ---------------------------------------------------------------------
create table if not exists public.solicitudes (
    id                uuid primary key default gen_random_uuid(),
    created_at        timestamptz not null default now(),
    user_id           uuid references auth.users(id) on delete set null,
    nombre            text,
    email             text,
    telefono          text,
    descripcion       text,
    paquete           text not null,
    precio_total_mxn  integer,
    anticipo_mxn      integer,
    acepto_anticipo   boolean default false,
    acepto_terminos   boolean default false,
    pago_estado       text default 'pendiente',   -- pendiente | pagado_anticipo
    stripe_session_id text
);

create index if not exists idx_solicitudes_created_at on public.solicitudes (created_at desc);
create index if not exists idx_solicitudes_user       on public.solicitudes (user_id);
create index if not exists idx_solicitudes_estado     on public.solicitudes (pago_estado);

alter table public.solicitudes enable row level security;

-- Un usuario autenticado solo puede crear/ver SUS propias solicitudes.
-- Los Edge Functions (service role) saltan RLS para actualizar el estado.
create policy "solicitud_insert_propia"
    on public.solicitudes for insert to authenticated
    with check (auth.uid() = user_id);

create policy "solicitud_select_propia"
    on public.solicitudes for select to authenticated
    using (auth.uid() = user_id);

-- ---------------------------------------------------------------------
--  CONTRATACIONES (ledger de pagos confirmados)
-- ---------------------------------------------------------------------
create table if not exists public.contrataciones (
    id                bigint generated by default as identity primary key,
    created_at        timestamptz not null default now(),
    paquete           text,
    precio_mxn        integer,          -- anticipo cobrado, en MXN
    cliente_nombre    text,
    cliente_email     text,
    stripe_session_id text unique,
    monto             integer,          -- monto en centavos, tal como lo da Stripe
    moneda            text default 'MXN',
    estado            text default 'paid'
);

create index if not exists idx_contrataciones_created_at on public.contrataciones (created_at desc);
create index if not exists idx_contrataciones_email       on public.contrataciones (cliente_email);

-- RLS activado sin políticas públicas: cerrada al público. Solo la
-- service role (webhook) escribe; tú lees desde el dashboard de Supabase.
alter table public.contrataciones enable row level security;
